name: Myrpg

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  EXECUTABLES: my_rpg
  MIRROR_URL: git@github.com:EpitechPromo2027/B-MUL-200-MAR-2-1-myrpg-theo.fabiano.git

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check coding style
      run: check.sh $(pwd) $(pwd)
    - name: Display annotations errors
      id: check_coding_style
      run: |
        if [ -s $(pwd)/coding-style-reports.log ]; then
          while read ligne; do
            echo "$ligne" | sed 's/\(.*\):\([0-9]*\): \(.*\):\([^-]*\)-\(.*\)/::error file=\1,line=\2,title=\3 coding style error::\4-\5/'
          done < $(pwd)/coding-style-reports.log
          echo "check_result=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "check_result=false" >> $GITHUB_OUTPUT
    - name: Notify Discord
      if: steps.check_coding_style.outputs.check_result == 'true'
      uses: cl8dep/action-discord@0.1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        username: '${{ env.EXECUTABLES }}'
        message: 'Error in coding style check job <@everyone>'
    - name: Exit with error if coding style check fails
      if: steps.check_coding_style.outputs.check_result == 'true'
      run: exit 1
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: make
        timeout-minutes: 2
      - name: Make clean
        run: make clean
      - name: Check executables
        id: check_executables
        run: |
          EXEC_ARRAY=( $(echo "${{ env.EXECUTABLES }}" | tr ',' ' ') )
          for executable in "${EXEC_ARRAY[@]}"; do
            if [ ! -x "$executable" ]; then
              echo "::error The executable file $executable does not exist or is not executable"
              echo "check_result=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "check_result=false" >> $GITHUB_OUTPUT
      - name: Notify Discord
        if: steps.check_executables.outputs.check_result == 'true'
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: '${{ env.EXECUTABLES }}'
          message: 'Error in program compilation check job <@everyone>'
      - name: Exit with error if program compilation check fails
        if: steps.check_executables.outputs.check_result == 'true'
        run: exit 1
  check_repository_size:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check repository size
        id: check_repository_size
        run: |
          size=$(du -sk --exclude=".git"  | awk '{print $1}')
          echo "Repository size: $size K"
          if [ "$size" -gt 30000 ]; then
            echo "Repository size exceeds 30 MB limit"
            echo "check_result=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "check_result=false" >> $GITHUB_OUTPUT
      - name: Notify Discord
        if: steps.check_repository_size.outputs.check_result == 'true'
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: '${{ env.EXECUTABLES }}'
          message: 'Error in repository size check job <@everyone>'
      - name: Exit with error if repository size check fails
        if: steps.check_repository_size.outputs.check_result == 'true'
        run: exit 1
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: check_repository_size
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: 
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}